---@type LangFile
return {
    misc = {
        text_none = "None",
        text_pause_schedule = "Schedule paused",
        text_random = "Random",
        text_disabled = "Disabled",
    },
    menu = {
        config = {
            name = "Mod",
            disable_button_cooldown = "Disable Button Cooldown",
            display_cheat_errors = "Display Cheat Errors",
            pause_schedule = "Pause Schedule",
            tooltip_pause_schedule = "Pauses schedule progression while the mod window is open",
        },
        language = {
            name = "Language",
            fallback = "Fallback",
            tooltip_fallback = "Display message in english if key is missing",
        },
        my_events = {
            name = "My Events",
        },
    },
    mod = {
        combo_event_type = "Event Type",
        combo_event_type_values = {
            monster = "Monster",
            gimmick = "Gimmick",
            animal = "Animal",
        },
        combo_event = "Event",
        combo_spoffer = "Second Monster",
        combo_area = "Area",
        combo_em_param = "Difficulty Param",
        combo_em_param_values = {
            legendary = "Tempered",
            frenzy = "Frenzied",
            normal = "Normal",
            swarm = "Swarm",
            boss = "Alpha",
            nushi = "Apex",
            battlefield_repel = "Battlefield Repel",
            battlefield_slay = "Battlefield Slay",
            pop_many2 = "Normal",
        },
        combo_em_param_mod = "Difficulty Mod",
        combo_em_param_mod_values = {
            none = "None",
            legendary = "Tempered",
            legendary_king = "Arch-Tempered",
        },
        combo_rewards = "Quest Rewards",
        combo_rewards_values = {
            disabled = "Random",
            user_defined = "User Defined",
        },
        slider_swarm_count = "Swarm Count",
        tooltip_swarm_count = "Number of extra monsters to include.\nRequires Difficulty Param to be set to Alpha or Swarm.\nSwarm monsters: ",
        slider_em_size = "Monster Size",
        crown = {
            small = "Small",
            large = "Large",
            king = "King",
        },
        slider_time = "Duration",
        box_ignore_environ = "Ignore Environment",
        tooltip_ignore_environ = "Bypass event environment requirement",
        box_yummy = "More Rewards",
        box_village_boost = "Gathering Boost",
        button_open_rewards_builder = "Edit Rewards",
        button_spawn = "Spawn",
        button_clear_schedule = "Clear Schedule",
        tootlip_clear_schedule = "Clear ALL events",
        button_rebuild_schedule = "Rebuild Schedule",
        tooltip_rebuild_schedule = "Clear schedule and fill with new events",
        text_wait = "Waiting for valid Stage...",
        table_event_headers = {
            header_event = "Event",
            header_area = "Area",
            header_remove_button = "",
        },
        button_remove_event = "Remove",
        text_em_swarm_suffix = "Swarm",
        tooltip_not_available = "Not available on this Stage",
        tooltip_event_error = {
            BAD_ENVIRONMENT = "This event can't be spawned while the current environment is active",
            EVENT_NOT_AVAILABLE = "This event is either not unlocked or something is preventing it from spawning",
        },
        input_reward_filter = "Filter",
        tooltip_reward_filter = "Filter by item name or ID",
        combo_reward = "Reward",
        slider_reward_count = "Amount",
        button_add_reward = "Add",
        table_reward_headers = {
            header_reward = "Reward",
            header_count = "Amount",
            header_remove_button = "",
        },
        button_remove_reward = "Remove",
        window_reward_builder = "Reward Builder",
        combo_em_param_difficulty = "Difficulty",
        tooltip_em_param_difficulty = "Purple Diamonds",
        combo_em_param_difficulty_rank = "Quest Rank",
        box_allow_invalid_quest = "Allow Invalid Quests",
        box_allow_exclusive_em = "Allow Exclusive Monsters",
        tooltip_allow_exclusive_em = "Allows 'exclusive' monsters to be selected as a secondary target in the Second Monster droplist.\nExclusive monsters: ",
        slider_spawn_delay = "Spawn Delay",
        tooltip_spawn_delay = "Delays the event by the specified amount of time.\nNote: Area might not work correctly.",
        tooltip_em_size = "Requires Difficulty to not be set to Random and Spawn Delay to be disabled",
        tooltip_category_difficulty = "Difficulty",
        tooltip_category_rewards = "Quest Rewards",
        tooltip_category_misc = "Misc",
        tooltip_category_spoffer = "Multi Monster Quest",
        tooltip_quest_rank = "Requires Difficulty to not be set to Random",
        tooltip_yummy = "Requires Quest Rewards to be set to Random",
        tooltip_village_boost = "Not available for Swarm and Battlefield",
        tooltip_spoffer = "Does not work while Spawn Delay is enabled",
    },
}
